### ISSUE TITLE
Do you have more quiz or exams to share?

### ISSUE THREAD

**Issue by Originofamonia** [NisargPawar/Distributed-Systems#1]
Hi Nisarg,

Thanks for your sharing the content. Do you have more quizzes or exams to share? Any help is much appreciated.

Thanks!

**Comment by NisargPawar** [comment]
Hi, I do have a few papers. Please share your email and ill send them to you.

**Comment by Originofamonia** [comment]
Hi,

Thanks for your reply.
My personal email is fugui.an@outlook.com<mailto:fugui.an@outlook.com>.

Thanks!
